//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 09:39:31 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import cn.szboc.uniformproxy.remoteinvoke.jaxb.bean.interfaces.CommonResponseMessage;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEAD" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_RESPONSE_HEAD"/>
 *         &lt;element name="BODY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UPDATE_METHOD" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_UPDATE_METHOD"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "A002_RESPONSE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem")
public class A002RESPONSE extends CommonResponseMessage {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "HEAD", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true)
    protected TRESPONSEHEAD head;
    @XmlElement(name = "BODY", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true)
    protected A002RESPONSE.BODY body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link TRESPONSEHEAD }
     *     
     */
    public TRESPONSEHEAD getHEAD() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRESPONSEHEAD }
     *     
     */
    public void setHEAD(TRESPONSEHEAD value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link A002RESPONSE.BODY }
     *     
     */
    public A002RESPONSE.BODY getBODY() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link A002RESPONSE.BODY }
     *     
     */
    public void setBODY(A002RESPONSE.BODY value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UPDATE_METHOD" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_UPDATE_METHOD"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "updatemethod"
    })
    public static class BODY implements Serializable{

		private static final long serialVersionUID = 1L;
		
		@XmlElement(name = "UPDATE_METHOD", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
        protected TUPDATEMETHOD updatemethod;

        /**
         * Gets the value of the updatemethod property.
         * 
         * @return
         *     possible object is
         *     {@link TUPDATEMETHOD }
         *     
         */
        public TUPDATEMETHOD getUPDATEMETHOD() {
            return updatemethod;
        }

        /**
         * Sets the value of the updatemethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUPDATEMETHOD }
         *     
         */
        public void setUPDATEMETHOD(TUPDATEMETHOD value) {
            this.updatemethod = value;
        }

    }

}
