//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.26 at 10:06:50 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import cn.szboc.uniformproxy.remoteinvoke.jaxb.bean.interfaces.CommonRequestMessage;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEAD" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_REQUEST_HEAD"/>
 *         &lt;element name="BODY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ACCOUNT_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ACCOUNT_NO"/>
 *                   &lt;element name="ACCOUNT_NAME" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ACCOUNT_NAME"/>
 *                   &lt;element name="ID_TYPE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ID_TYPE"/>
 *                   &lt;element name="ID_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ID_NO"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "C001_REQUEST")
public class C001REQUEST extends CommonRequestMessage{

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "HEAD", required = true)
    protected TREQUESTHEAD head;
    @XmlElement(name = "BODY", required = true)
    protected C001REQUEST.BODY body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link TREQUESTHEAD }
     *     
     */
    public TREQUESTHEAD getHEAD() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link TREQUESTHEAD }
     *     
     */
    public void setHEAD(TREQUESTHEAD value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link C001REQUEST.BODY }
     *     
     */
    public C001REQUEST.BODY getBODY() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link C001REQUEST.BODY }
     *     
     */
    public void setBODY(C001REQUEST.BODY value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ACCOUNT_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ACCOUNT_NO"/>
     *         &lt;element name="ACCOUNT_NAME" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ACCOUNT_NAME"/>
     *         &lt;element name="ID_TYPE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ID_TYPE"/>
     *         &lt;element name="ID_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_ID_NO"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountno",
        "accountname",
        "idtype",
        "idno"
    })
    public static class BODY implements Serializable {

		private static final long serialVersionUID = 1L;
		
		@XmlElement(name = "ACCOUNT_NO", required = true)
        protected String accountno;
        @XmlElement(name = "ACCOUNT_NAME", required = true)
        protected String accountname;
        @XmlElement(name = "ID_TYPE", required = true, nillable = true)
        protected TIDTYPE idtype;
        @XmlElement(name = "ID_NO", required = true, nillable = true)
        protected String idno;

        /**
         * Gets the value of the accountno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNTNO() {
            return accountno;
        }

        /**
         * Sets the value of the accountno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNTNO(String value) {
            this.accountno = value;
        }

        /**
         * Gets the value of the accountname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNTNAME() {
            return accountname;
        }

        /**
         * Sets the value of the accountname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNTNAME(String value) {
            this.accountname = value;
        }

        /**
         * Gets the value of the idtype property.
         * 
         * @return
         *     possible object is
         *     {@link TIDTYPE }
         *     
         */
        public TIDTYPE getIDTYPE() {
            return idtype;
        }

        /**
         * Sets the value of the idtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIDTYPE }
         *     
         */
        public void setIDTYPE(TIDTYPE value) {
            this.idtype = value;
        }

        /**
         * Gets the value of the idno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIDNO() {
            return idno;
        }

        /**
         * Sets the value of the idno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIDNO(String value) {
            this.idno = value;
        }

    }


	@Override
	public TTRANSMSGTYPE getTransType() {
		return TTRANSMSGTYPE.C_001;
	}

	@Override
	public String getArgumentInfo() {
		// TODO Auto-generated method stub
		return null;
	}

}
