//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 09:39:31 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.szboc.uniformproxy.remoteinvoke.jaxb.bean2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.szboc.uniformproxy.remoteinvoke.jaxb.bean2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TREQUESTHEAD }
     * 
     */
    public TREQUESTHEAD createTREQUESTHEAD() {
        return new TREQUESTHEAD();
    }

    /**
     * Create an instance of {@link A001RESPONSE }
     * 
     */
    public A001RESPONSE createA001RESPONSE() {
        return new A001RESPONSE();
    }

    /**
     * Create an instance of {@link TSINGLETRANSACTIONRESULT }
     * 
     */
    public TSINGLETRANSACTIONRESULT createTSINGLETRANSACTIONRESULT() {
        return new TSINGLETRANSACTIONRESULT();
    }

    /**
     * Create an instance of {@link TBATCHHEADV2 }
     * 
     */
    public TBATCHHEADV2 createTBATCHHEADV2() {
        return new TBATCHHEADV2();
    }

    /**
     * Create an instance of {@link C103REQUEST.BODY }
     * 
     */
    public C103REQUEST.BODY createC103REQUESTBODY() {
        return new C103REQUEST.BODY();
    }

    /**
     * Create an instance of {@link C003RESPONSE.BODY }
     * 
     */
    public C003RESPONSE.BODY createC003RESPONSEBODY() {
        return new C003RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link C102REQUEST.BODY }
     * 
     */
    public C102REQUEST.BODY createC102REQUESTBODY() {
        return new C102REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B005RESPONSE.BODY }
     * 
     */
    public B005RESPONSE.BODY createB005RESPONSEBODY() {
        return new B005RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link TTRANSDETAILV2 }
     * 
     */
    public TTRANSDETAILV2 createTTRANSDETAILV2() {
        return new TTRANSDETAILV2();
    }

    /**
     * Create an instance of {@link C104REQUEST.BODY }
     * 
     */
    public C104REQUEST.BODY createC104REQUESTBODY() {
        return new C104REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B105RESPONSE.BODY }
     * 
     */
    public B105RESPONSE.BODY createB105RESPONSEBODY() {
        return new B105RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link C003REQUEST.BODY }
     * 
     */
    public C003REQUEST.BODY createC003REQUESTBODY() {
        return new C003REQUEST.BODY();
    }

    /**
     * Create an instance of {@link C004RESPONSE.BODY.DETAILS }
     * 
     */
    public C004RESPONSE.BODY.DETAILS createC004RESPONSEBODYDETAILS() {
        return new C004RESPONSE.BODY.DETAILS();
    }

    /**
     * Create an instance of {@link A001REQUEST.BODY }
     * 
     */
    public A001REQUEST.BODY createA001REQUESTBODY() {
        return new A001REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B004REQUEST }
     * 
     */
    public B004REQUEST createB004REQUEST() {
        return new B004REQUEST();
    }

    /**
     * Create an instance of {@link C103RESPONSE.BODY.BATCH }
     * 
     */
    public C103RESPONSE.BODY.BATCH createC103RESPONSEBODYBATCH() {
        return new C103RESPONSE.BODY.BATCH();
    }

    /**
     * Create an instance of {@link A002RESPONSE.BODY }
     * 
     */
    public A002RESPONSE.BODY createA002RESPONSEBODY() {
        return new A002RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B001REQUEST }
     * 
     */
    public B001REQUEST createB001REQUEST() {
        return new B001REQUEST();
    }

    /**
     * Create an instance of {@link TBATCHDETAIL }
     * 
     */
    public TBATCHDETAIL createTBATCHDETAIL() {
        return new TBATCHDETAIL();
    }

    /**
     * Create an instance of {@link A001RESPONSE.BODY }
     * 
     */
    public A001RESPONSE.BODY createA001RESPONSEBODY() {
        return new A001RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link TACCOUNTRESULTDETAILV2 }
     * 
     */
    public TACCOUNTRESULTDETAILV2 createTACCOUNTRESULTDETAILV2() {
        return new TACCOUNTRESULTDETAILV2();
    }

    /**
     * Create an instance of {@link C003RESPONSE }
     * 
     */
    public C003RESPONSE createC003RESPONSE() {
        return new C003RESPONSE();
    }

    /**
     * Create an instance of {@link C104RESPONSE.BODY.DETAILS }
     * 
     */
    public C104RESPONSE.BODY.DETAILS createC104RESPONSEBODYDETAILS() {
        return new C104RESPONSE.BODY.DETAILS();
    }

    /**
     * Create an instance of {@link C003REQUEST }
     * 
     */
    public C003REQUEST createC003REQUEST() {
        return new C003REQUEST();
    }

    /**
     * Create an instance of {@link C004RESPONSE.BODY }
     * 
     */
    public C004RESPONSE.BODY createC004RESPONSEBODY() {
        return new C004RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B004REQUEST.BODY }
     * 
     */
    public B004REQUEST.BODY createB004REQUESTBODY() {
        return new B004REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B104REQUEST.BODY }
     * 
     */
    public B104REQUEST.BODY createB104REQUESTBODY() {
        return new B104REQUEST.BODY();
    }

    /**
     * Create an instance of {@link C104RESPONSE }
     * 
     */
    public C104RESPONSE createC104RESPONSE() {
        return new C104RESPONSE();
    }

    /**
     * Create an instance of {@link C102REQUEST }
     * 
     */
    public C102REQUEST createC102REQUEST() {
        return new C102REQUEST();
    }

    /**
     * Create an instance of {@link C001REQUEST.BODY }
     * 
     */
    public C001REQUEST.BODY createC001REQUESTBODY() {
        return new C001REQUEST.BODY();
    }

    /**
     * Create an instance of {@link A002REQUEST.BODY }
     * 
     */
    public A002REQUEST.BODY createA002REQUESTBODY() {
        return new A002REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B005REQUEST.BODY }
     * 
     */
    public B005REQUEST.BODY createB005REQUESTBODY() {
        return new B005REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B001RESPONSE }
     * 
     */
    public B001RESPONSE createB001RESPONSE() {
        return new B001RESPONSE();
    }

    /**
     * Create an instance of {@link TTRANSDETAIL }
     * 
     */
    public TTRANSDETAIL createTTRANSDETAIL() {
        return new TTRANSDETAIL();
    }

    /**
     * Create an instance of {@link C103RESPONSE }
     * 
     */
    public C103RESPONSE createC103RESPONSE() {
        return new C103RESPONSE();
    }

    /**
     * Create an instance of {@link C002REQUEST.BODY }
     * 
     */
    public C002REQUEST.BODY createC002REQUESTBODY() {
        return new C002REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B004RESPONSE }
     * 
     */
    public B004RESPONSE createB004RESPONSE() {
        return new B004RESPONSE();
    }

    /**
     * Create an instance of {@link C003RESPONSE.BODY.BATCH }
     * 
     */
    public C003RESPONSE.BODY.BATCH createC003RESPONSEBODYBATCH() {
        return new C003RESPONSE.BODY.BATCH();
    }

    /**
     * Create an instance of {@link TBATCHTRANSDETAILV2 }
     * 
     */
    public TBATCHTRANSDETAILV2 createTBATCHTRANSDETAILV2() {
        return new TBATCHTRANSDETAILV2();
    }

    /**
     * Create an instance of {@link C102RESPONSE }
     * 
     */
    public C102RESPONSE createC102RESPONSE() {
        return new C102RESPONSE();
    }

    /**
     * Create an instance of {@link C103RESPONSE.BODY }
     * 
     */
    public C103RESPONSE.BODY createC103RESPONSEBODY() {
        return new C103RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B003REQUEST }
     * 
     */
    public B003REQUEST createB003REQUEST() {
        return new B003REQUEST();
    }

    /**
     * Create an instance of {@link C104RESPONSE.BODY }
     * 
     */
    public C104RESPONSE.BODY createC104RESPONSEBODY() {
        return new C104RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B002REQUEST }
     * 
     */
    public B002REQUEST createB002REQUEST() {
        return new B002REQUEST();
    }

    /**
     * Create an instance of {@link B104REQUEST }
     * 
     */
    public B104REQUEST createB104REQUEST() {
        return new B104REQUEST();
    }

    /**
     * Create an instance of {@link A001REQUEST }
     * 
     */
    public A001REQUEST createA001REQUEST() {
        return new A001REQUEST();
    }

    /**
     * Create an instance of {@link C002RESPONSE }
     * 
     */
    public C002RESPONSE createC002RESPONSE() {
        return new C002RESPONSE();
    }

    /**
     * Create an instance of {@link B002RESPONSE }
     * 
     */
    public B002RESPONSE createB002RESPONSE() {
        return new B002RESPONSE();
    }

    /**
     * Create an instance of {@link B003RESPONSE.BODY }
     * 
     */
    public B003RESPONSE.BODY createB003RESPONSEBODY() {
        return new B003RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link C003RESPONSE.BODY.DETAILS }
     * 
     */
    public C003RESPONSE.BODY.DETAILS createC003RESPONSEBODYDETAILS() {
        return new C003RESPONSE.BODY.DETAILS();
    }

    /**
     * Create an instance of {@link A002REQUEST }
     * 
     */
    public A002REQUEST createA002REQUEST() {
        return new A002REQUEST();
    }

    /**
     * Create an instance of {@link TRESPONSEHEAD }
     * 
     */
    public TRESPONSEHEAD createTRESPONSEHEAD() {
        return new TRESPONSEHEAD();
    }

    /**
     * Create an instance of {@link C004REQUEST.BODY }
     * 
     */
    public C004REQUEST.BODY createC004REQUESTBODY() {
        return new C004REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B105RESPONSE }
     * 
     */
    public B105RESPONSE createB105RESPONSE() {
        return new B105RESPONSE();
    }

    /**
     * Create an instance of {@link B102REQUEST }
     * 
     */
    public B102REQUEST createB102REQUEST() {
        return new B102REQUEST();
    }

    /**
     * Create an instance of {@link TBATCHDETAILV2 }
     * 
     */
    public TBATCHDETAILV2 createTBATCHDETAILV2() {
        return new TBATCHDETAILV2();
    }

    /**
     * Create an instance of {@link C001RESPONSE }
     * 
     */
    public C001RESPONSE createC001RESPONSE() {
        return new C001RESPONSE();
    }

    /**
     * Create an instance of {@link C103REQUEST }
     * 
     */
    public C103REQUEST createC103REQUEST() {
        return new C103REQUEST();
    }

    /**
     * Create an instance of {@link C004RESPONSE }
     * 
     */
    public C004RESPONSE createC004RESPONSE() {
        return new C004RESPONSE();
    }

    /**
     * Create an instance of {@link C104REQUEST }
     * 
     */
    public C104REQUEST createC104REQUEST() {
        return new C104REQUEST();
    }

    /**
     * Create an instance of {@link B005RESPONSE }
     * 
     */
    public B005RESPONSE createB005RESPONSE() {
        return new B005RESPONSE();
    }

    /**
     * Create an instance of {@link B101RESPONSE }
     * 
     */
    public B101RESPONSE createB101RESPONSE() {
        return new B101RESPONSE();
    }

    /**
     * Create an instance of {@link B004RESPONSE.BODY }
     * 
     */
    public B004RESPONSE.BODY createB004RESPONSEBODY() {
        return new B004RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B005REQUEST }
     * 
     */
    public B005REQUEST createB005REQUEST() {
        return new B005REQUEST();
    }

    /**
     * Create an instance of {@link B102RESPONSE }
     * 
     */
    public B102RESPONSE createB102RESPONSE() {
        return new B102RESPONSE();
    }

    /**
     * Create an instance of {@link B003REQUEST.BODY }
     * 
     */
    public B003REQUEST.BODY createB003REQUESTBODY() {
        return new B003REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B003RESPONSE }
     * 
     */
    public B003RESPONSE createB003RESPONSE() {
        return new B003RESPONSE();
    }

    /**
     * Create an instance of {@link C001RESPONSE.BODY }
     * 
     */
    public C001RESPONSE.BODY createC001RESPONSEBODY() {
        return new C001RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B101REQUEST }
     * 
     */
    public B101REQUEST createB101REQUEST() {
        return new B101REQUEST();
    }

    /**
     * Create an instance of {@link TACCOUNTRESULTDETAIL }
     * 
     */
    public TACCOUNTRESULTDETAIL createTACCOUNTRESULTDETAIL() {
        return new TACCOUNTRESULTDETAIL();
    }

    /**
     * Create an instance of {@link TBATCHHEAD }
     * 
     */
    public TBATCHHEAD createTBATCHHEAD() {
        return new TBATCHHEAD();
    }

    /**
     * Create an instance of {@link B104RESPONSE.BODY }
     * 
     */
    public B104RESPONSE.BODY createB104RESPONSEBODY() {
        return new B104RESPONSE.BODY();
    }

    /**
     * Create an instance of {@link B105REQUEST }
     * 
     */
    public B105REQUEST createB105REQUEST() {
        return new B105REQUEST();
    }

    /**
     * Create an instance of {@link B105REQUEST.BODY }
     * 
     */
    public B105REQUEST.BODY createB105REQUESTBODY() {
        return new B105REQUEST.BODY();
    }

    /**
     * Create an instance of {@link B104RESPONSE }
     * 
     */
    public B104RESPONSE createB104RESPONSE() {
        return new B104RESPONSE();
    }

    /**
     * Create an instance of {@link C002REQUEST }
     * 
     */
    public C002REQUEST createC002REQUEST() {
        return new C002REQUEST();
    }

    /**
     * Create an instance of {@link C001REQUEST }
     * 
     */
    public C001REQUEST createC001REQUEST() {
        return new C001REQUEST();
    }

    /**
     * Create an instance of {@link A002RESPONSE }
     * 
     */
    public A002RESPONSE createA002RESPONSE() {
        return new A002RESPONSE();
    }

    /**
     * Create an instance of {@link C103RESPONSE.BODY.DETAILS }
     * 
     */
    public C103RESPONSE.BODY.DETAILS createC103RESPONSEBODYDETAILS() {
        return new C103RESPONSE.BODY.DETAILS();
    }

    /**
     * Create an instance of {@link C004REQUEST }
     * 
     */
    public C004REQUEST createC004REQUEST() {
        return new C004REQUEST();
    }

}
