//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.16 at 10:28:18 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for T_ACCOUNT_RESULT_DETAIL_V2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_ACCOUNT_RESULT_DETAIL_V2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TRANS_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_TRANS_NO"/>
 *         &lt;element name="DEDUCT_RTN_CODE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_RESULT_CODE"/>
 *         &lt;element name="ROLLBACK_RTN_CODE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_RESULT_CODE"/>
 *         &lt;element name="TRANS_STATUS" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_STATUS_CODE"/>
 *         &lt;element name="TRANS_MSG_TYPE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_TRANS_MSG_TYPE"/>
 *         &lt;element name="TRANS_AMT" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_MONEY"/>
 *         &lt;element name="HANDLE_FEE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_MONEY"/>
 *         &lt;element name="ACTUAL_DEDUCT_AMT" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_MONEY"/>
 *         &lt;element name="HANDLE_FEE_TYPE" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_HANDLE_FEE_TYPE"/>
 *         &lt;element name="ACCOUNT_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TRANS_DESC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_ACCOUNT_RESULT_DETAIL_V2", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", propOrder = {
    "transno",
    "deductrtncode",
    "rollbackrtncode",
    "transstatus",
    "transmsgtype",
    "transamt",
    "handlefee",
    "actualdeductamt",
    "handlefeetype",
    "accountdate",
    "transdesc"
})
public class TACCOUNTRESULTDETAILV2 implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "TRANS_NO", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected String transno;
    @XmlElement(name = "DEDUCT_RTN_CODE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected TRESULTCODE deductrtncode;
    @XmlElement(name = "ROLLBACK_RTN_CODE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected TRESULTCODE rollbackrtncode;
    @XmlElement(name = "TRANS_STATUS", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected TSTATUSCODE transstatus;
    @XmlElement(name = "TRANS_MSG_TYPE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected TTRANSMSGTYPE transmsgtype;
    @XmlElement(name = "TRANS_AMT", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected BigDecimal transamt;
    @XmlElement(name = "HANDLE_FEE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected BigDecimal handlefee;
    @XmlElement(name = "ACTUAL_DEDUCT_AMT", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected BigDecimal actualdeductamt;
    @XmlElement(name = "HANDLE_FEE_TYPE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected THANDLEFEETYPE handlefeetype;
    @XmlElement(name = "ACCOUNT_DATE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, type = String.class, nillable = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date accountdate;
    @XmlElement(name = "TRANS_DESC", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem", required = true, nillable = true)
    protected String transdesc;

    /**
     * Gets the value of the transno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSNO() {
        return transno;
    }

    /**
     * Sets the value of the transno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSNO(String value) {
        this.transno = value;
    }

    /**
     * Gets the value of the deductrtncode property.
     * 
     * @return
     *     possible object is
     *     {@link TRESULTCODE }
     *     
     */
    public TRESULTCODE getDEDUCTRTNCODE() {
        return deductrtncode;
    }

    /**
     * Sets the value of the deductrtncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRESULTCODE }
     *     
     */
    public void setDEDUCTRTNCODE(TRESULTCODE value) {
        this.deductrtncode = value;
    }

    /**
     * Gets the value of the rollbackrtncode property.
     * 
     * @return
     *     possible object is
     *     {@link TRESULTCODE }
     *     
     */
    public TRESULTCODE getROLLBACKRTNCODE() {
        return rollbackrtncode;
    }

    /**
     * Sets the value of the rollbackrtncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRESULTCODE }
     *     
     */
    public void setROLLBACKRTNCODE(TRESULTCODE value) {
        this.rollbackrtncode = value;
    }

    /**
     * Gets the value of the transstatus property.
     * 
     * @return
     *     possible object is
     *     {@link TSTATUSCODE }
     *     
     */
    public TSTATUSCODE getTRANSSTATUS() {
        return transstatus;
    }

    /**
     * Sets the value of the transstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSTATUSCODE }
     *     
     */
    public void setTRANSSTATUS(TSTATUSCODE value) {
        this.transstatus = value;
    }

    /**
     * Gets the value of the transmsgtype property.
     * 
     * @return
     *     possible object is
     *     {@link TTRANSMSGTYPE }
     *     
     */
    public TTRANSMSGTYPE getTRANSMSGTYPE() {
        return transmsgtype;
    }

    /**
     * Sets the value of the transmsgtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTRANSMSGTYPE }
     *     
     */
    public void setTRANSMSGTYPE(TTRANSMSGTYPE value) {
        this.transmsgtype = value;
    }

    /**
     * Gets the value of the transamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTRANSAMT() {
        return transamt;
    }

    /**
     * Sets the value of the transamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTRANSAMT(BigDecimal value) {
        this.transamt = value;
    }

    /**
     * Gets the value of the handlefee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHANDLEFEE() {
        return handlefee;
    }

    /**
     * Sets the value of the handlefee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHANDLEFEE(BigDecimal value) {
        this.handlefee = value;
    }

    /**
     * Gets the value of the actualdeductamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getACTUALDEDUCTAMT() {
        return actualdeductamt;
    }

    /**
     * Sets the value of the actualdeductamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setACTUALDEDUCTAMT(BigDecimal value) {
        this.actualdeductamt = value;
    }

    /**
     * Gets the value of the handlefeetype property.
     * 
     * @return
     *     possible object is
     *     {@link THANDLEFEETYPE }
     *     
     */
    public THANDLEFEETYPE getHANDLEFEETYPE() {
        return handlefeetype;
    }

    /**
     * Sets the value of the handlefeetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link THANDLEFEETYPE }
     *     
     */
    public void setHANDLEFEETYPE(THANDLEFEETYPE value) {
        this.handlefeetype = value;
    }

    /**
     * Gets the value of the accountdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getACCOUNTDATE() {
        return accountdate;
    }

    /**
     * Sets the value of the accountdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTDATE(Date value) {
        this.accountdate = value;
    }

    /**
     * Gets the value of the transdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSDESC() {
        return transdesc;
    }

    /**
     * Sets the value of the transdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSDESC(String value) {
        this.transdesc = value;
    }

}
