//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.27 at 10:12:35 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_BATCH_HEAD", propOrder = {
    "packno",
    "count",
    "sum"
})
public class TBATCHHEAD implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "PACK_NO", required = true)
    protected String packno;
    @XmlElement(name = "COUNT")
    protected int count;
    @XmlElement(name = "SUM", required = true)
    protected BigDecimal sum;

    /**
     * Gets the value of the packno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKNO() {
        return packno;
    }

    /**
     * Sets the value of the packno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKNO(String value) {
        this.packno = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCOUNT() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCOUNT(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSUM() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSUM(BigDecimal value) {
        this.sum = value;
    }

}
