//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 09:17:41 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_BATCH_HEAD_V2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T_BATCH_HEAD_V2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PACK_NO" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_PACK_NO"/>
 *         &lt;element name="COUNT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUM" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_MONEY"/>
 *         &lt;element name="USE_ITEM" type="{http://www.szboc.cn/projects/open/2012/UniformProxySystem}T_USE_ITEM"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_BATCH_HEAD_V2", propOrder = {
    "packno",
    "count",
    "sum",
    "useitem"
})
public class TBATCHHEADV2 implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "PACK_NO", required = true)
    protected String packno;
    @XmlElement(name = "COUNT")
    protected int count;
    @XmlElement(name = "SUM", required = true)
    protected BigDecimal sum;
    @XmlElement(name = "USE_ITEM", required = true)
    protected String useitem;

    /**
     * Gets the value of the packno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKNO() {
        return packno;
    }

    /**
     * Sets the value of the packno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKNO(String value) {
        this.packno = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCOUNT() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCOUNT(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSUM() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSUM(BigDecimal value) {
        this.sum = value;
    }

    /**
     * Gets the value of the useitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSEITEM() {
        return useitem;
    }

    /**
     * Sets the value of the useitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSEITEM(String value) {
        this.useitem = value;
    }

}
