//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.26 at 10:06:50 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "T_HANDLE_FEE_TYPE")
@XmlEnum
public enum THANDLEFEETYPE{

    @XmlEnumValue("F0")
    F_0("F0"),
    @XmlEnumValue("F1")
    F_1("F1"),
    @XmlEnumValue("F2")
    F_2("F2");
    private final String value;

    THANDLEFEETYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static THANDLEFEETYPE fromValue(String v) {
        for (THANDLEFEETYPE c: THANDLEFEETYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
