//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.26 at 10:06:50 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "T_ID_TYPE")
@XmlEnum
public enum TIDTYPE {

    @XmlEnumValue("P01")
    P_01("P01"),
    @XmlEnumValue("P02")
    P_02("P02"),
    @XmlEnumValue("P03")
    P_03("P03"),
    @XmlEnumValue("P04")
    P_04("P04"),
    @XmlEnumValue("P05")
    P_05("P05"),
    @XmlEnumValue("P06")
    P_06("P06"),
    @XmlEnumValue("P07")
    P_07("P07"),
    @XmlEnumValue("P08")
    P_08("P08"),
    @XmlEnumValue("P09")
    P_09("P09"),
    @XmlEnumValue("P10")
    P_10("P10"),
    @XmlEnumValue("P11")
    P_11("P11"),
    @XmlEnumValue("P47")
    P_47("P47"),
    @XmlEnumValue("P48")
    P_48("P48"),
    @XmlEnumValue("P49")
    P_49("P49"),
    @XmlEnumValue("C21")
    C_21("C21"),
    @XmlEnumValue("C22")
    C_22("C22"),
    @XmlEnumValue("C23")
    C_23("C23"),
    @XmlEnumValue("C24")
    C_24("C24"),
    @XmlEnumValue("C25")
    C_25("C25"),
    @XmlEnumValue("C26")
    C_26("C26"),
    @XmlEnumValue("C27")
    C_27("C27"),
    @XmlEnumValue("C28")
    C_28("C28"),
    @XmlEnumValue("C29")
    C_29("C29"),
    @XmlEnumValue("C30")
    C_30("C30"),
    @XmlEnumValue("C31")
    C_31("C31"),
    @XmlEnumValue("C32")
    C_32("C32"),
    @XmlEnumValue("C33")
    C_33("C33"),
    @XmlEnumValue("C34")
    C_34("C34"),
    @XmlEnumValue("C35")
    C_35("C35"),
    @XmlEnumValue("C36")
    C_36("C36"),
    @XmlEnumValue("C37")
    C_37("C37"),
    @XmlEnumValue("C38")
    C_38("C38"),
    @XmlEnumValue("C39")
    C_39("C39"),
    @XmlEnumValue("C40")
    C_40("C40"),
    @XmlEnumValue("C41")
    C_41("C41"),
    @XmlEnumValue("C42")
    C_42("C42"),
    @XmlEnumValue("C43")
    C_43("C43"),
    @XmlEnumValue("C44")
    C_44("C44");
    private final String value;

    TIDTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TIDTYPE fromValue(String v) {
        for (TIDTYPE c: TIDTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
