//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.26 at 03:11:22 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "T_RESULT_CODE")
@XmlEnum
public enum TRESULTCODE {

    @XmlEnumValue("R0000")
    SUCCESS("R0000"),
    
    @XmlEnumValue("R0404")
    SERVICE_NOT_AVALIABLE("R0404"),
    
    @XmlEnumValue("R0405")
    MSG_FORMAT_ERROR("R0405"),
    
    @XmlEnumValue("R1000")
    AMOUNT_INSUFFICIENT("R1000"),
    
    @XmlEnumValue("R2000")
    ACCOUNT_STATUS_INVALID("R2000"),
    
    @XmlEnumValue("R3000")
    CHANNEL_CLOSED("R3000"),
    
    @XmlEnumValue("R4000")
    TRANSACTION_NOT_EXISTS("R4000"),
    
    @XmlEnumValue("R4001")
    TRANSACTION_PROCESSING("R4001"),
    
    @XmlEnumValue("R5000")
    REF_TRANSACTION_FAILURE("R5000"),
    
    @XmlEnumValue("R5001")
    REF_TRANSACTION_ROLLBACKED("R5001"),
    
    @XmlEnumValue("R6000")
    ELEMENT_ERROR("R6000"),
    
    @XmlEnumValue("R6201")
    ACCOUNT_NOT_EXISTS("R6201"),
    
    @XmlEnumValue("R6202")
    ACCOUNT_NAME_NOT_MATCH("R6202"),
    
    @XmlEnumValue("R6203")
    ID_INFO_NOT_EXISTS("R6203"),
    
    @XmlEnumValue("R6204")
    ID_TYPE_NOT_MATCH("R6204"),
    
    @XmlEnumValue("R6205")
    ID_NO_NOT_MATCH("R6205"),
    
    @XmlEnumValue("R8000")
    TRANSACTION_FAILURE("R8000"),
    
    @XmlEnumValue("R9000")
    BANK_EXCEPTION("R9000");
    

    private final String value;

    TRESULTCODE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRESULTCODE fromValue(String v) {
    	if(v == null){
    		return null;
    	}
        for (TRESULTCODE c: TRESULTCODE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
