//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.16 at 10:28:18 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for T_TRANS_MSG_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="T_TRANS_MSG_TYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A001"/>
 *     &lt;enumeration value="A002"/>
 *     &lt;enumeration value="B001"/>
 *     &lt;enumeration value="B002"/>
 *     &lt;enumeration value="B003"/>
 *     &lt;enumeration value="B004"/>
 *     &lt;enumeration value="B005"/>
 *     &lt;enumeration value="B101"/>
 *     &lt;enumeration value="B102"/>
 *     &lt;enumeration value="B104"/>
 *     &lt;enumeration value="B105"/>
 *     &lt;enumeration value="C001"/>
 *     &lt;enumeration value="C002"/>
 *     &lt;enumeration value="C003"/>
 *     &lt;enumeration value="C004"/>
 *     &lt;enumeration value="C102"/>
 *     &lt;enumeration value="C103"/>
 *     &lt;enumeration value="C104"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "T_TRANS_MSG_TYPE", namespace = "http://www.szboc.cn/projects/open/2012/UniformProxySystem")
@XmlEnum
public enum TTRANSMSGTYPE {

    @XmlEnumValue("A001")
    A_001("A001"),
    @XmlEnumValue("A002")
    A_002("A002"),
    @XmlEnumValue("B001")
    B_001("B001"),
    @XmlEnumValue("B002")
    B_002("B002"),
    @XmlEnumValue("B003")
    B_003("B003"),
    @XmlEnumValue("B004")
    B_004("B004"),
    @XmlEnumValue("B005")
    B_005("B005"),
    @XmlEnumValue("B101")
    B_101("B101"),
    @XmlEnumValue("B102")
    B_102("B102"),
    @XmlEnumValue("B104")
    B_104("B104"),
    @XmlEnumValue("B105")
    B_105("B105"),
    @XmlEnumValue("C001")
    C_001("C001"),
    @XmlEnumValue("C002")
    C_002("C002"),
    @XmlEnumValue("C003")
    C_003("C003"),
    @XmlEnumValue("C004")
    C_004("C004"),
    @XmlEnumValue("C102")
    C_102("C102"),
    @XmlEnumValue("C103")
    C_103("C103"),
    @XmlEnumValue("C104")
    C_104("C104");
    private final String value;

    TTRANSMSGTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTRANSMSGTYPE fromValue(String v) {
        for (TTRANSMSGTYPE c: TTRANSMSGTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
