//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.26 at 10:06:50 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.jaxb.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_TRANS_DETAIL", propOrder = {
    "transno",
    "transdate",
    "accountno",
    "accountname",
    "money",
    "idtype",
    "idno",
    "agreementno",
    "useitem",
    "postscript"
})
public class TTRANSDETAIL implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "TRANS_NO", required = true)
    protected String transno;
    @XmlElement(name = "TRANS_DATE", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date transdate;
    @XmlElement(name = "ACCOUNT_NO", required = true)
    protected String accountno;
    @XmlElement(name = "ACCOUNT_NAME", required = true)
    protected String accountname;
    @XmlElement(name = "MONEY", required = true)
    protected BigDecimal money;
    @XmlElement(name = "ID_TYPE", required = true, nillable = true)
    protected TIDTYPE idtype;
    @XmlElement(name = "ID_NO", required = true, nillable = true)
    protected String idno;
    @XmlElement(name = "AGREEMENT_NO", required = true, nillable = true)
    protected String agreementno;
    @XmlElement(name = "USE_ITEM", required = true)
    protected String useitem;
    @XmlElement(name = "POST_SCRIPT", required = true, nillable = true)
    protected String postscript;

    /**
     * Gets the value of the transno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSNO() {
        return transno;
    }

    /**
     * Sets the value of the transno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSNO(String value) {
        this.transno = value;
    }

    /**
     * Gets the value of the transdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getTRANSDATE() {
        return transdate;
    }

    /**
     * Sets the value of the transdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSDATE(Date value) {
        this.transdate = value;
    }

    /**
     * Gets the value of the accountno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNO() {
        return accountno;
    }

    /**
     * Sets the value of the accountno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNO(String value) {
        this.accountno = value;
    }

    /**
     * Gets the value of the accountname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNAME() {
        return accountname;
    }

    /**
     * Sets the value of the accountname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNAME(String value) {
        this.accountname = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMONEY() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMONEY(BigDecimal value) {
        this.money = value;
    }

    /**
     * Gets the value of the idtype property.
     * 
     * @return
     *     possible object is
     *     {@link TIDTYPE }
     *     
     */
    public TIDTYPE getIDTYPE() {
        return idtype;
    }

    /**
     * Sets the value of the idtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIDTYPE }
     *     
     */
    public void setIDTYPE(TIDTYPE value) {
        this.idtype = value;
    }

    /**
     * Gets the value of the idno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNO() {
        return idno;
    }

    /**
     * Sets the value of the idno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNO(String value) {
        this.idno = value;
    }

    /**
     * Gets the value of the agreementno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGREEMENTNO() {
        return agreementno;
    }

    /**
     * Sets the value of the agreementno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGREEMENTNO(String value) {
        this.agreementno = value;
    }

    /**
     * Gets the value of the useitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSEITEM() {
        return useitem;
    }

    /**
     * Sets the value of the useitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSEITEM(String value) {
        this.useitem = value;
    }
    
    /**
     * Gets the value of the postscript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTSCRIPT() {
        return postscript;
    }

    /**
     * Sets the value of the postscript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTSCRIPT(String value) {
        this.postscript = value;
    }

}
