//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 01:31:30 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.batch.bean.recv;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="oes_batch_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trade_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="batch_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="custom_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pay_channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="act_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="term_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trans_net" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="act_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="curr_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="total_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="total_amt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="recv_ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="recv_port" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="record">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="seq_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pay_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pay_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="payee_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="payee_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="payee_bank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="payee_bank_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pay_money" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="use_item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="msg_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id_card" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="extend_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="rtn_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="rtn_msg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "root")
public class BatchDeductResponseRecvBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(required = true)
    protected BatchDeductResponseRecvBean.Header header;
    @XmlElement(required = true)
    protected BatchDeductResponseRecvBean.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link BatchDeductResponseRecvBean.Header }
     *     
     */
    public BatchDeductResponseRecvBean.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchDeductResponseRecvBean.Header }
     *     
     */
    public void setHeader(BatchDeductResponseRecvBean.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link BatchDeductResponseRecvBean.Body }
     *     
     */
    public BatchDeductResponseRecvBean.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchDeductResponseRecvBean.Body }
     *     
     */
    public void setBody(BatchDeductResponseRecvBean.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="record">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="seq_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pay_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pay_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="payee_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="payee_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="payee_bank" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="payee_bank_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pay_money" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="use_item" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="msg_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id_card" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="extend_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="rtn_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="rtn_msg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "record"
    })
    public static class Body implements Serializable {

		private static final long serialVersionUID = 1L;
		
		protected List<BatchDeductResponseRecvBean.Body.Record> record;

        /**
         * Gets the value of the record property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the record property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BatchDeductResponseRecvBean.Body.Record }
         * 
         * 
         */
        public List<BatchDeductResponseRecvBean.Body.Record> getRecord() {
            if (record == null) {
                record = new ArrayList<BatchDeductResponseRecvBean.Body.Record>();
            }
            return this.record;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="seq_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pay_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pay_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="payee_act" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="payee_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="payee_bank" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="payee_bank_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pay_money" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="use_item" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="msg_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id_card" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="extend_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="rtn_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="rtn_msg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "seqNo",
            "payAct",
            "payName",
            "payeeAct",
            "payeeName",
            "payeeBank",
            "payeeBankNo",
            "payMoney",
            "useItem",
            "msgFlag",
            "idCard",
            "extendValue",
            "rtnCode",
            "rtnMsg"
        })
        public static class Record implements Serializable {

			private static final long serialVersionUID = 1L;
			
			@XmlElement(name = "seq_no", required = true)
            protected String seqNo;
            @XmlElement(name = "pay_act", required = true)
            protected String payAct;
            @XmlElement(name = "pay_name", required = true)
            protected String payName;
            @XmlElement(name = "payee_act", required = true)
            protected String payeeAct;
            @XmlElement(name = "payee_name", required = true)
            protected String payeeName;
            @XmlElement(name = "payee_bank", required = true)
            protected String payeeBank;
            @XmlElement(name = "payee_bank_no", required = true)
            protected String payeeBankNo;
            @XmlElement(name = "pay_money")
            protected double payMoney;
            @XmlElement(name = "use_item", required = true)
            protected String useItem;
            @XmlElement(name = "msg_flag", required = true)
            protected String msgFlag;
            @XmlElement(name = "id_card", required = true)
            protected String idCard;
            @XmlElement(name = "extend_value", required = true)
            protected String extendValue;
            @XmlElement(name = "rtn_code", required = true)
            protected String rtnCode;
            @XmlElement(name = "rtn_msg", required = true)
            protected String rtnMsg;

            /**
             * Gets the value of the seqNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeqNo() {
                return seqNo;
            }

            /**
             * Sets the value of the seqNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeqNo(String value) {
                this.seqNo = value;
            }

            /**
             * Gets the value of the payAct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayAct() {
                return payAct;
            }

            /**
             * Sets the value of the payAct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayAct(String value) {
                this.payAct = value;
            }

            /**
             * Gets the value of the payName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayName() {
                return payName;
            }

            /**
             * Sets the value of the payName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayName(String value) {
                this.payName = value;
            }

            /**
             * Gets the value of the payeeAct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeAct() {
                return payeeAct;
            }

            /**
             * Sets the value of the payeeAct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeAct(String value) {
                this.payeeAct = value;
            }

            /**
             * Gets the value of the payeeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeName() {
                return payeeName;
            }

            /**
             * Sets the value of the payeeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeName(String value) {
                this.payeeName = value;
            }

            /**
             * Gets the value of the payeeBank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeBank() {
                return payeeBank;
            }

            /**
             * Sets the value of the payeeBank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeBank(String value) {
                this.payeeBank = value;
            }

            /**
             * Gets the value of the payeeBankNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeBankNo() {
                return payeeBankNo;
            }

            /**
             * Sets the value of the payeeBankNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeBankNo(String value) {
                this.payeeBankNo = value;
            }

            /**
             * Gets the value of the payMoney property.
             * 
             */
            public double getPayMoney() {
                return payMoney;
            }

            /**
             * Sets the value of the payMoney property.
             * 
             */
            public void setPayMoney(double value) {
                this.payMoney = value;
            }

            /**
             * Gets the value of the useItem property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseItem() {
                return useItem;
            }

            /**
             * Sets the value of the useItem property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseItem(String value) {
                this.useItem = value;
            }

            /**
             * Gets the value of the msgFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgFlag() {
                return msgFlag;
            }

            /**
             * Sets the value of the msgFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgFlag(String value) {
                this.msgFlag = value;
            }

            /**
             * Gets the value of the idCard property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdCard() {
                return idCard;
            }

            /**
             * Sets the value of the idCard property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdCard(String value) {
                this.idCard = value;
            }

            /**
             * Gets the value of the extendValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtendValue() {
                return extendValue;
            }

            /**
             * Sets the value of the extendValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtendValue(String value) {
                this.extendValue = value;
            }

            /**
             * Gets the value of the rtnCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRtnCode() {
                return rtnCode;
            }

            /**
             * Sets the value of the rtnCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRtnCode(String value) {
                this.rtnCode = value;
            }

            /**
             * Gets the value of the rtnMsg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRtnMsg() {
                return rtnMsg;
            }

            /**
             * Sets the value of the rtnMsg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRtnMsg(String value) {
                this.rtnMsg = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="oes_batch_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trade_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="batch_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="custom_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pay_channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="act_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="term_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trans_net" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="act_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="curr_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="total_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="total_amt" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="recv_ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="recv_port" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oesBatchNo",
        "tradeType",
        "batchNo",
        "customCode",
        "payChannel",
        "actMode",
        "termFlag",
        "transNet",
        "actNo",
        "currCode",
        "totalCount",
        "totalAmt",
        "recvIp",
        "recvPort"
    })
    public static class Header implements Serializable {

		private static final long serialVersionUID = 1L;
		
		@XmlElement(name = "oes_batch_no", required = true)
        protected String oesBatchNo;
        @XmlElement(name = "trade_type", required = true)
        protected String tradeType;
        @XmlElement(name = "batch_no", required = true)
        protected String batchNo;
        @XmlElement(name = "custom_code", required = true)
        protected String customCode;
        @XmlElement(name = "pay_channel", required = true)
        protected String payChannel;
        @XmlElement(name = "act_mode", required = true)
        protected String actMode;
        @XmlElement(name = "term_flag", required = true)
        protected String termFlag;
        @XmlElement(name = "trans_net", required = true)
        protected String transNet;
        @XmlElement(name = "act_no", required = true)
        protected String actNo;
        @XmlElement(name = "curr_code", required = true)
        protected String currCode;
        @XmlElement(name = "total_count")
        protected int totalCount;
        @XmlElement(name = "total_amt")
        protected double totalAmt;
        @XmlElement(name = "recv_ip", required = true)
        protected String recvIp;
        @XmlElement(name = "recv_port", required = true)
        protected String recvPort;

        /**
         * Gets the value of the oesBatchNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOesBatchNo() {
            return oesBatchNo;
        }

        /**
         * Sets the value of the oesBatchNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOesBatchNo(String value) {
            this.oesBatchNo = value;
        }

        /**
         * Gets the value of the tradeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTradeType() {
            return tradeType;
        }

        /**
         * Sets the value of the tradeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTradeType(String value) {
            this.tradeType = value;
        }

        /**
         * Gets the value of the batchNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBatchNo() {
            return batchNo;
        }

        /**
         * Sets the value of the batchNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBatchNo(String value) {
            this.batchNo = value;
        }

        /**
         * Gets the value of the customCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomCode() {
            return customCode;
        }

        /**
         * Sets the value of the customCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomCode(String value) {
            this.customCode = value;
        }

        /**
         * Gets the value of the payChannel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayChannel() {
            return payChannel;
        }

        /**
         * Sets the value of the payChannel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayChannel(String value) {
            this.payChannel = value;
        }

        /**
         * Gets the value of the actMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActMode() {
            return actMode;
        }

        /**
         * Sets the value of the actMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActMode(String value) {
            this.actMode = value;
        }

        /**
         * Gets the value of the termFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermFlag() {
            return termFlag;
        }

        /**
         * Sets the value of the termFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermFlag(String value) {
            this.termFlag = value;
        }

        /**
         * Gets the value of the transNet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransNet() {
            return transNet;
        }

        /**
         * Sets the value of the transNet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransNet(String value) {
            this.transNet = value;
        }

        /**
         * Gets the value of the actNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActNo() {
            return actNo;
        }

        /**
         * Sets the value of the actNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActNo(String value) {
            this.actNo = value;
        }

        /**
         * Gets the value of the currCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrCode() {
            return currCode;
        }

        /**
         * Sets the value of the currCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrCode(String value) {
            this.currCode = value;
        }

        /**
         * Gets the value of the totalCount property.
         * 
         */
        public int getTotalCount() {
            return totalCount;
        }

        /**
         * Sets the value of the totalCount property.
         * 
         */
        public void setTotalCount(int value) {
            this.totalCount = value;
        }

        /**
         * Gets the value of the totalAmt property.
         * 
         */
        public double getTotalAmt() {
            return totalAmt;
        }

        /**
         * Sets the value of the totalAmt property.
         * 
         */
        public void setTotalAmt(double value) {
            this.totalAmt = value;
        }

        /**
         * Gets the value of the recvIp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecvIp() {
            return recvIp;
        }

        /**
         * Sets the value of the recvIp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecvIp(String value) {
            this.recvIp = value;
        }

        /**
         * Gets the value of the recvPort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecvPort() {
            return recvPort;
        }

        /**
         * Sets the value of the recvPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecvPort(String value) {
            this.recvPort = value;
        }

    }

}
