//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 01:31:30 ���� CST 
//


package cn.szboc.uniformproxy.remoteinvoke.batch.bean.recv;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.szboc.uniformproxy.remoteinvoke.batch.bean.recv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.szboc.uniformproxy.remoteinvoke.batch.bean.recv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BatchDeductResponseRecvBean.Header }
     * 
     */
    public BatchDeductResponseRecvBean.Header createRootHeader() {
        return new BatchDeductResponseRecvBean.Header();
    }

    /**
     * Create an instance of {@link BatchDeductResponseRecvBean.Body }
     * 
     */
    public BatchDeductResponseRecvBean.Body createRootBody() {
        return new BatchDeductResponseRecvBean.Body();
    }

    /**
     * Create an instance of {@link BatchDeductResponseRecvBean.Body.Record }
     * 
     */
    public BatchDeductResponseRecvBean.Body.Record createRootBodyRecord() {
        return new BatchDeductResponseRecvBean.Body.Record();
    }

    /**
     * Create an instance of {@link BatchDeductResponseRecvBean }
     * 
     */
    public BatchDeductResponseRecvBean createRoot() {
        return new BatchDeductResponseRecvBean();
    }

}
